### ISSUE TITLE
Codes of Mnist experiments

### ISSUE THREAD

**Issue by GUOShuxuan** [flennerhag/alstm#5]
Hello,

It is a very impressive work. Is it possible to release the codes for the mnist, which is such a simple sample that helps understand the proposed method well.

**Comment by flennerhag** [comment]
Hi, thanks! :-)

I don't have any plans on releasing a full code base as it's basically the tensorflow [mnist tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist) with an sva layer instead of a linear layer in the ``inference`` function in the [mnist.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist.py#L45) file. You can use the below implementation for SVA:

```python
def sva(input, adapt_units, output_units, training, dropout, name=None):
    """Adaptive feed-forward layer using singular value adaptation"""
    
    input_units = input.get_shape()[1].value

    with tf.variable_scope(name):
        Q = tf.Variable(
            tf.orthogonal_initializer()([input_units, 2 * adapt_units]), name='Q')
        P = tf.Variable(
            tf.orthogonal_initializer()([adapt_units, output_units]), name='P')
        B = tf.Variable(tf.zeros([output_units]), name='b')

    ud = tf.matmul(input, Q)
    u, d = tf.split(ud, 2, axis=1)
    u = tf.multiply(u, d)
    h = tf.matmul(u, P) + B
    h = tf.layers.dropout(h, dropout, training=training)
    return h
``` 

Just replace the ``Hidden-1`` layer (and ``Hidden-2`` layer too if you want to) with the ``sva`` function above. Hope this helps - don't hesitate to reach out otherwise!
